# Generated by Django 4.1 on 2024-02-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='login',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='data',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
