# Generated by Django 4.1 on 2024-02-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_data_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='isDelated',
            field=models.CharField(choices=[('DEL', 'Delete'), ('EXI', 'Exists')], default='EXI', max_length=3),
        ),
    ]
